// Small hand-written examples. Lectures without a matching set start with no quiz;
// students can add questions that match their own notes in the quiz setup screen.
const questionSets = {
  "Equations of Conic- Quarter 1_Module 5": [
    { question: "Which equation represents a circle with center (h, k) and radius r?", options: ["(x − h)² + (y − k)² = r²", "(x − h)²/a² + (y − k)²/b² = 1", "y − k = m(x − h)", "x² = 4py"], answer: "(x − h)² + (y − k)² = r²" },
    { question: "Which equation is the standard form of a vertical parabola with vertex at the origin?", options: ["x² = 4py", "y² = 4px", "x² + y² = r²", "x²/a² − y²/b² = 1"], answer: "x² = 4py" },
    { question: "Which standard equation describes an ellipse centered at the origin?", options: ["x²/a² + y²/b² = 1", "x²/a² − y²/b² = 1", "y = mx + b", "x² = 4py"], answer: "x²/a² + y²/b² = 1" },
    { question: "Which feature distinguishes the standard equation of a hyperbola from that of an ellipse?", options: ["The squared terms are subtracted", "There are no squared terms", "It has only one variable", "The squared terms are always added"], answer: "The squared terms are subtracted" },
    { question: "In x² = 4py, what does the sign of p determine?", options: ["The direction the parabola opens", "The length of the major axis", "The circle's radius", "The slope of an asymptote"], answer: "The direction the parabola opens" },
    { question: "Where is the center of (x − 3)² + (y + 2)² = 25?", options: ["(3, −2)", "(−3, 2)", "(3, 2)", "(−3, −2)"], answer: "(3, −2)" },
    { question: "What is the radius of (x − 1)² + (y − 4)² = 9?", options: ["3", "9", "6", "√3"], answer: "3" },
    { question: "For an ellipse, which point is the center in the equation (x − h)²/a² + (y − k)²/b² = 1?", options: ["(h, k)", "(a, b)", "(−h, −k)", "(0, 0) in every case"], answer: "(h, k)" },
    { question: "A hyperbola with a horizontal transverse axis has which squared term first in its standard form?", options: ["The x-term is positive", "The y-term is positive", "Both terms are positive", "Neither term is squared"], answer: "The x-term is positive" },
  ],
  "Antimicrobial Susceptibility Testing": [
    { question: "Which value is the lowest antimicrobial concentration that prevents visible bacterial growth?", options: ["MIC", "MBC", "Zone diameter", "Inoculum density"], answer: "MIC" },
    { question: "In disk diffusion testing, what is measured around an antimicrobial disk?", options: ["A zone of inhibition", "A red cell count", "A pH change", "A colony's mass"], answer: "A zone of inhibition" },
    { question: "What does a larger zone of inhibition generally indicate for a susceptible organism?", options: ["Greater inhibition by the antimicrobial", "More bacterial growth", "A higher MIC", "A contaminated plate"], answer: "Greater inhibition by the antimicrobial" },
    { question: "What does MBC stand for?", options: ["Minimum bactericidal concentration", "Maximum bacterial count", "Minimum broth culture", "Measured bacterial change"], answer: "Minimum bactericidal concentration" },
    { question: "Why is a standardized inoculum used in susceptibility testing?", options: ["To make results comparable", "To change the antibiotic", "To color the medium", "To prevent incubation"], answer: "To make results comparable" },
    { question: "What does AST stand for?", options: ["Antimicrobial susceptibility testing", "Antibody screening technique", "Automated stain test", "Antigen sensitivity titer"], answer: "Antimicrobial susceptibility testing" },
    { question: "Which method commonly uses antibiotic-impregnated disks on agar?", options: ["Disk diffusion", "Gram staining", "Coagulation testing", "ELISA"], answer: "Disk diffusion" },
    { question: "What is compared with interpretive breakpoints to categorize susceptibility?", options: ["The measured test result", "The patient's age", "The color of the disk", "The agar brand name"], answer: "The measured test result" },
    { question: "What does MBC measure?", options: ["The lowest concentration that kills the organism", "The largest inhibition zone", "The total bacterial count", "The time needed to stain bacteria"], answer: "The lowest concentration that kills the organism" },
    { question: "Why should susceptibility results be interpreted with organism identification?", options: ["Breakpoints can depend on the organism", "Every organism has the same response", "It replaces quality control", "It changes the incubation temperature"], answer: "Breakpoints can depend on the organism" },
  ],
  "Liver Function Tests": [
    { question: "Which enzyme is commonly elevated with hepatocellular injury?", options: ["ALT", "Amylase", "Troponin", "CK-MB"], answer: "ALT" },
    { question: "Which test is commonly used to assess the liver's synthetic function?", options: ["Prothrombin time", "Serum sodium", "Lipase", "Uric acid"], answer: "Prothrombin time" },
    { question: "A rise in alkaline phosphatase is most associated with which pattern?", options: ["Cholestasis", "Hemolysis", "Pancreatitis", "Renal failure"], answer: "Cholestasis" },
    { question: "Which pigment is measured in tests of bilirubin?", options: ["Heme breakdown product", "Ketone body", "Bile acid enzyme", "Plasma protein"], answer: "Heme breakdown product" },
    { question: "Which protein is produced by the liver and often measured in a chemistry panel?", options: ["Albumin", "Insulin", "Myoglobin", "Hemoglobin"], answer: "Albumin" },
    { question: "Which enzyme is more concentrated in liver cells than AST and is commonly used for liver injury?", options: ["ALT", "CK", "Amylase", "ALP only"], answer: "ALT" },
    { question: "Which bilirubin fraction is water-soluble after conjugation in the liver?", options: ["Conjugated bilirubin", "Unconjugated bilirubin", "Hemoglobin", "Urobilinogen only"], answer: "Conjugated bilirubin" },
    { question: "A prolonged prothrombin time may reflect reduced production of what?", options: ["Clotting factors", "Bile pigments", "Red cell membranes", "Pancreatic enzymes"], answer: "Clotting factors" },
    { question: "Which pattern is most consistent with cholestasis?", options: ["Raised alkaline phosphatase", "Low troponin", "Raised creatine kinase only", "Low amylase"], answer: "Raised alkaline phosphatase" },
    { question: "Why can albumin be low in chronic liver disease?", options: ["Reduced hepatic synthesis", "Increased red cell production", "Blocked insulin release", "Increased bone turnover"], answer: "Reduced hepatic synthesis" },
  ],
  "RBC Morphology": [
    { question: "What does the term microcytic describe?", options: ["Red cells smaller than normal", "Red cells larger than normal", "Red cells without a nucleus", "Red cells with two nuclei"], answer: "Red cells smaller than normal" },
    { question: "Which term describes variation in red cell shape?", options: ["Poikilocytosis", "Anisocytosis", "Leukocytosis", "Thrombocytopenia"], answer: "Poikilocytosis" },
    { question: "What is a hypochromic red cell?", options: ["A cell with increased central pallor", "A cell with no central pallor", "A fragmented cell", "A sickle-shaped cell"], answer: "A cell with increased central pallor" },
    { question: "What does anisocytosis refer to?", options: ["Variation in red cell size", "Variation in red cell shape", "A low platelet count", "An increased white cell count"], answer: "Variation in red cell size" },
    { question: "Which red cell shape is classically crescent-shaped?", options: ["Sickle cell", "Spherocyte", "Target cell", "Schistocyte"], answer: "Sickle cell" },
    { question: "What does macrocytic describe?", options: ["Red cells larger than normal", "Red cells smaller than normal", "Low platelet count", "Increased central pallor"], answer: "Red cells larger than normal" },
    { question: "Which red cell has a bull's-eye appearance?", options: ["Target cell", "Spherocyte", "Schistocyte", "Sickle cell"], answer: "Target cell" },
    { question: "What is a schistocyte?", options: ["A fragmented red cell", "A round red cell without pallor", "A large platelet", "A nucleated lymphocyte"], answer: "A fragmented red cell" },
    { question: "Which term means increased variation in red cell size?", options: ["Anisocytosis", "Poikilocytosis", "Leukopenia", "Polychromasia"], answer: "Anisocytosis" },
    { question: "What does polychromasia on a blood film often indicate?", options: ["Young red cells in circulation", "Absence of platelets", "Bacterial contamination", "A low white cell count"], answer: "Young red cells in circulation" },
  ],
  "Culture Media": [
    { question: "What is the main purpose of selective culture media?", options: ["To inhibit some organisms while allowing others to grow", "To count red cells", "To measure antibody levels", "To determine blood group"], answer: "To inhibit some organisms while allowing others to grow" },
    { question: "What does differential media help distinguish?", options: ["Organisms by visible biochemical reactions", "Cell sizes in blood", "Antibody classes", "Antibiotic concentrations in serum"], answer: "Organisms by visible biochemical reactions" },
    { question: "Which ingredient often makes MacConkey agar selective for Gram-negative bacteria?", options: ["Bile salts", "Blood cells", "Urea", "Starch"], answer: "Bile salts" },
    { question: "What does a pure culture contain?", options: ["One microbial species", "Several unrelated species", "Only viruses", "No living organisms"], answer: "One microbial species" },
    { question: "Why is agar commonly used in solid culture media?", options: ["It provides a solid surface for colonies", "It identifies antibodies", "It stains bacterial capsules", "It supplies oxygen"], answer: "It provides a solid surface for colonies" },
    { question: "What is enriched media designed to do?", options: ["Support growth of fastidious organisms", "Inhibit every organism", "Measure antibody concentration", "Separate serum proteins"], answer: "Support growth of fastidious organisms" },
    { question: "What is the purpose of a transport medium?", options: ["Maintain a specimen during transit", "Identify every organism by color", "Increase antibiotic resistance", "Replace incubation"], answer: "Maintain a specimen during transit" },
    { question: "What does a colony represent on solid agar?", options: ["Growth from a viable cell or group of cells", "A single molecule of agar", "An antibiotic disk", "A stain precipitate"], answer: "Growth from a viable cell or group of cells" },
    { question: "Which medium is both selective and differential for many enteric bacteria?", options: ["MacConkey agar", "Nutrient broth", "Saline", "Blood collection tube"], answer: "MacConkey agar" },
    { question: "Why are culture plates incubated under specified conditions?", options: ["Growth depends on temperature and atmosphere", "It sterilizes the specimen", "It removes all contaminants", "It fixes cell morphology"], answer: "Growth depends on temperature and atmosphere" },
  ],
  "Antigen and Antibody Reactions": [
    { question: "What is an antigen?", options: ["A substance recognized by an immune response", "A type of red blood cell", "A clotting factor", "A digestive enzyme"], answer: "A substance recognized by an immune response" },
    { question: "What is an antibody?", options: ["An immunoglobulin that binds a specific antigen", "A bacterial culture medium", "A platelet fragment", "A liver enzyme"], answer: "An immunoglobulin that binds a specific antigen" },
    { question: "What visible event defines agglutination?", options: ["Clumping of particulate antigens", "Dissolving of red cells", "Clot formation", "Bacterial movement"], answer: "Clumping of particulate antigens" },
    { question: "Which antibody class is most abundant in serum?", options: ["IgG", "IgE", "IgD", "IgM"], answer: "IgG" },
    { question: "What is needed for a visible antigen-antibody reaction?", options: ["Suitable antigen and antibody proportions", "A very high temperature only", "No antigen", "A bacterial enzyme"], answer: "Suitable antigen and antibody proportions" },
    { question: "Which immunoglobulin is typically produced first in a primary immune response?", options: ["IgM", "IgG", "IgA", "IgE"], answer: "IgM" },
    { question: "Which immunoglobulin is common in mucosal secretions?", options: ["IgA", "IgD", "IgE", "IgM"], answer: "IgA" },
    { question: "What is the prozone effect?", options: ["Excess antibody can prevent visible lattice formation", "Excess antigen always causes hemolysis", "An antigen changes its blood group", "An antibody becomes an enzyme"], answer: "Excess antibody can prevent visible lattice formation" },
    { question: "What occurs during precipitation?", options: ["Soluble antigen and antibody form an insoluble lattice", "Red cells divide", "Bacteria form colonies", "Platelets release hemoglobin"], answer: "Soluble antigen and antibody form an insoluble lattice" },
    { question: "Which part of an antibody binds a specific antigen epitope?", options: ["Variable region", "Constant region only", "Hinge only", "Fc receptor"], answer: "Variable region" },
  ],
};

export default questionSets;
